services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "hypercorn app.main:app --bind 0.0.0.0:10000 --workers 4 --worker-class asyncio --access-log - --error-log - --log-level info --graceful-timeout 30 --keep-alive 2"
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: "/health"
    disk:
      name: fastapi-data
      mountPath: /opt/render/project/data
      sizeGB: 1