"""add is_visible to table

Revision ID: 10822f099780
Revises: 5a3117e7d530
Create Date: 2025-06-07 02:02:30.297752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10822f099780'
down_revision: Union[str, None] = '5a3117e7d530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_visible', sa.Boolean(), nullable=True), schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_visible', schema='portfolio_pro_app')
    # ### end Alembic commands ###
