"""add auth_id to table

Revision ID: 15f55777e392
Revises: 5f3955a95364
Create Date: 2025-07-03 02:08:42.597973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f55777e392'
down_revision: Union[str, None] = '5f3955a95364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. First add column as nullable
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=True), schema='portfolio_pro_app')
    
    # 2. Set default values for existing rows (choose one option):
    # Option A: For UUIDs (recommended if using auth)
    op.execute("UPDATE portfolio_pro_app.users SET auth_id = gen_random_uuid()::text WHERE auth_id IS NULL")
    
    # Option B: For incremental numbers
    # op.execute("UPDATE portfolio_pro_app.users SET auth_id = 'user_' || id::text WHERE auth_id IS NULL")
    
    # 3. Now alter column to be NOT NULL
    op.alter_column('users', 'auth_id', nullable=False, schema='portfolio_pro_app')
    
    # 4. Create the unique index
    op.create_index(
        op.f('ix_portfolio_pro_app_users_auth_id'), 
        'users', 
        ['auth_id'], 
        unique=True, 
        schema='portfolio_pro_app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_pro_app_users_auth_id'), table_name='users', schema='portfolio_pro_app')
    op.drop_column('users', 'auth_id', schema='portfolio_pro_app')
    # ### end Alembic commands ###