"""add new_model table

Revision ID: 1cedf1b856e5
Revises: 957697742fc0
Create Date: 2025-06-11 21:19:58.509107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cedf1b856e5'
down_revision: Union[str, None] = '957697742fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('alert', 'message', 'system', name='notificationtype', schema='portfolio_pro_app'),
               type_=postgresql.ENUM('alert', 'message', 'system', name='notificationtype'),
               nullable=True,
               schema='portfolio_pro_app')
    # ### end Alembic commands ###
