"""add new columns to user settings table 

Revision ID: 384ffc035a29
Revises: 97e1eac20a18
Create Date: 2025-07-07 02:22:51.224189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384ffc035a29'
down_revision: Union[str, None] = '97e1eac20a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('accent', sa.String(), nullable=True), schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'accent', schema='portfolio_pro_app')
    # ### end Alembic commands ###
