"""user contribution description

Revision ID: 385e3dc003a0
Revises: ff8cad9276da
Create Date: 2025-06-07 23:29:27.117210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385e3dc003a0'
down_revision: Union[str, None] = 'ff8cad9276da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_association', sa.Column('contribution_description', sa.String(), nullable=True), schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_project_association', 'contribution_description', schema='portfolio_pro_app')
    # ### end Alembic commands ###
