"""added auth_id to User table

Revision ID: 3bc9bca8ec83
Revises: 7b086250f684
Create Date: 2025-07-03 02:35:15.586912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc9bca8ec83'
down_revision: Union[str, None] = '7b086250f684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['auth_id'], schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='portfolio_pro_app', type_='unique')
    # ### end Alembic commands ###
