"""initial

Revision ID: 41c316548d93
Revises: 
Create Date: 2025-06-06 16:05:09.957534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c316548d93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_users_email'), 'users', ['email'], unique=True, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_users_firstname'), 'users', ['firstname'], unique=False, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_users_id'), 'users', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_users_lastname'), 'users', ['lastname'], unique=False, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_users_middlename'), 'users', ['middlename'], unique=False, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_users_username'), 'users', ['username'], unique=True, schema='portfolio_pro_app')
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('certification_name', sa.String(), nullable=False),
    sa.Column('issuing_organization', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_certifications_id'), 'certifications', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('content_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_content_blocks_id'), 'content_blocks', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('custom_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_custom_sections_id'), 'custom_sections', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_education_id'), 'education', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('media_gallery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_media_gallery_id'), 'media_gallery', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('portfolio_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('project_description', sa.String(), nullable=False),
    sa.Column('project_url', sa.String(), nullable=True),
    sa.Column('project_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_portfolio_projects_id'), 'portfolio_projects', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('professional_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('proficiency_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_professional_skills_id'), 'professional_skills', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('social_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_social_links_id'), 'social_links', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_title', sa.String(), nullable=True),
    sa.Column('author_company', sa.String(), nullable=True),
    sa.Column('author_relationship', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_testimonials_id'), 'testimonials', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('open_to_work', sa.Boolean(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_user_profile_id'), 'user_profile', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('primary_theme', sa.String(), nullable=True),
    sa.Column('secondary_theme', sa.String(), nullable=True),
    sa.Column('layout_style', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_user_settings_id'), 'user_settings', ['id'], unique=False, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_user_settings_language'), 'user_settings', ['language'], unique=False, schema='portfolio_pro_app')
    op.create_table('custom_section_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['portfolio_pro_app.custom_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_custom_section_items_id'), 'custom_section_items', ['id'], unique=False, schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_pro_app_custom_section_items_id'), table_name='custom_section_items', schema='portfolio_pro_app')
    op.drop_table('custom_section_items', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_user_settings_language'), table_name='user_settings', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_user_settings_id'), table_name='user_settings', schema='portfolio_pro_app')
    op.drop_table('user_settings', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_user_profile_id'), table_name='user_profile', schema='portfolio_pro_app')
    op.drop_table('user_profile', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_testimonials_id'), table_name='testimonials', schema='portfolio_pro_app')
    op.drop_table('testimonials', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_social_links_id'), table_name='social_links', schema='portfolio_pro_app')
    op.drop_table('social_links', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_professional_skills_id'), table_name='professional_skills', schema='portfolio_pro_app')
    op.drop_table('professional_skills', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_portfolio_projects_id'), table_name='portfolio_projects', schema='portfolio_pro_app')
    op.drop_table('portfolio_projects', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_media_gallery_id'), table_name='media_gallery', schema='portfolio_pro_app')
    op.drop_table('media_gallery', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_education_id'), table_name='education', schema='portfolio_pro_app')
    op.drop_table('education', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_custom_sections_id'), table_name='custom_sections', schema='portfolio_pro_app')
    op.drop_table('custom_sections', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_content_blocks_id'), table_name='content_blocks', schema='portfolio_pro_app')
    op.drop_table('content_blocks', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_certifications_id'), table_name='certifications', schema='portfolio_pro_app')
    op.drop_table('certifications', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_users_username'), table_name='users', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_users_middlename'), table_name='users', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_users_lastname'), table_name='users', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_users_id'), table_name='users', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_users_firstname'), table_name='users', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_users_email'), table_name='users', schema='portfolio_pro_app')
    op.drop_table('users', schema='portfolio_pro_app')
    # ### end Alembic commands ###
