"""add new_model table

Revision ID: 522265d1e5c1
Revises: 41c316548d93
Create Date: 2025-06-06 17:08:27.474828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522265d1e5c1'
down_revision: Union[str, None] = '41c316548d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index(op.f('ix_portfolio_pro_app_user_devices_id'), 'user_devices', ['id'], unique=False, schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_pro_app_user_devices_id'), table_name='user_devices', schema='portfolio_pro_app')
    op.drop_table('user_devices', schema='portfolio_pro_app')
    # ### end Alembic commands ###
