"""Convert user-project to many-to-many

Revision ID: 5a3117e7d530
Revises: 629fb1d12eb1
Create Date: 2025-06-06 23:21:20.478961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3117e7d530'
down_revision: Union[str, None] = '629fb1d12eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['portfolio_pro_app.project_comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['portfolio_pro_app.portfolio_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_table('project_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['portfolio_pro_app.portfolio_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_likes', schema='portfolio_pro_app')
    op.drop_table('project_comments', schema='portfolio_pro_app')
    # ### end Alembic commands ###
