"""Added the suggestion model as planned

Revision ID: 5f3955a95364
Revises: fbd7836b1d55
Create Date: 2025-06-14 16:58:43.565517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3955a95364'
down_revision: Union[str, None] = 'fbd7836b1d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_table('suggestion_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['portfolio_pro_app.suggestion_comments.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['portfolio_pro_app.suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_table('suggestion_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('suggestion_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['portfolio_pro_app.suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'suggestion_id', name='uq_user_suggestion_vote'),
    schema='portfolio_pro_app'
    )
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               schema='portfolio_pro_app')
    op.drop_table('suggestion_votes', schema='portfolio_pro_app')
    op.drop_table('suggestion_comments', schema='portfolio_pro_app')
    op.drop_table('suggestions', schema='portfolio_pro_app')
    # ### end Alembic commands ###
