"""add new_model table

Revision ID: 72af4e656a12
Revises: 3bc9bca8ec83
Create Date: 2025-07-03 18:30:16.853214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72af4e656a12'
down_revision: Union[str, None] = '3bc9bca8ec83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('loader', sa.String(), nullable=True), schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'loader', schema='portfolio_pro_app')
    # ### end Alembic commands ###
