"""added notification  table

Revision ID: 957697742fc0
Revises: d1dcadc2ed64
Create Date: 2025-06-11 18:04:25.346356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957697742fc0'
down_revision: Union[str, None] = 'd1dcadc2ed64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.Enum('ALERT', 'MESSAGE', 'SYSTEM', name='notificationtype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['portfolio_pro_app.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portfolio_pro_app'
    )
    op.create_index('idx_notification_created', 'notifications', ['created_at'], unique=False, schema='portfolio_pro_app')
    op.create_index('idx_notification_user_unread', 'notifications', ['user_id', 'is_read'], unique=False, schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_user_unread', table_name='notifications', schema='portfolio_pro_app')
    op.drop_index('idx_notification_created', table_name='notifications', schema='portfolio_pro_app')
    op.drop_table('notifications', schema='portfolio_pro_app')
    # ### end Alembic commands ###
