"""add new_model table

Revision ID: 97e1eac20a18
Revises: 72af4e656a12
Create Date: 2025-07-05 08:49:44.365725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e1eac20a18'
down_revision: Union[str, None] = '72af4e656a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('primary_theme_dark', sa.String(), nullable=True), schema='portfolio_pro_app')
    op.add_column('user_settings', sa.Column('secondary_theme_dark', sa.String(), nullable=True), schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'secondary_theme_dark', schema='portfolio_pro_app')
    op.drop_column('user_settings', 'primary_theme_dark', schema='portfolio_pro_app')
    # ### end Alembic commands ###
