"""add author id  to testimonial table

Revision ID: a8ccfddd2ad3
Revises: 10822f099780
Create Date: 2025-06-07 02:28:35.700283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ccfddd2ad3'
down_revision: Union[str, None] = '10822f099780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('author_user_id', sa.UUID(), nullable=True), schema='portfolio_pro_app')
    op.create_foreign_key(None, 'testimonials', 'users', ['author_user_id'], ['id'], source_schema='portfolio_pro_app', referent_schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testimonials', schema='portfolio_pro_app', type_='foreignkey')
    op.drop_column('testimonials', 'author_user_id', schema='portfolio_pro_app')
    # ### end Alembic commands ###
