"""added portfolio  table

Revision ID: b2b19a8db889
Revises: 345e15c4c395
Create Date: 2025-06-07 19:03:12.768249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b19a8db889'
down_revision: Union[str, None] = '345e15c4c395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portfolio_pro_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_user_portfolio_slug'),
    schema='portfolio_pro_app'
    )
    op.create_index('idx_portfolio_user', 'portfolios', ['user_id'], unique=False, schema='portfolio_pro_app')
    op.create_index(op.f('ix_portfolio_pro_app_portfolios_is_public'), 'portfolios', ['is_public'], unique=False, schema='portfolio_pro_app')
    op.create_table('portfolio_project_associations',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_pro_app.portfolios.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['portfolio_pro_app.portfolio_projects.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'project_id'),
    schema='portfolio_pro_app'
    )
    op.create_index('idx_portfolio_order', 'portfolio_project_associations', ['portfolio_id', 'position'], unique=False, schema='portfolio_pro_app')
    op.create_index('idx_portfolio_project', 'portfolio_project_associations', ['portfolio_id', 'project_id'], unique=False, schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_portfolio_project', table_name='portfolio_project_associations', schema='portfolio_pro_app')
    op.drop_index('idx_portfolio_order', table_name='portfolio_project_associations', schema='portfolio_pro_app')
    op.drop_table('portfolio_project_associations', schema='portfolio_pro_app')
    op.drop_index(op.f('ix_portfolio_pro_app_portfolios_is_public'), table_name='portfolios', schema='portfolio_pro_app')
    op.drop_index('idx_portfolio_user', table_name='portfolios', schema='portfolio_pro_app')
    op.drop_table('portfolios', schema='portfolio_pro_app')
    # ### end Alembic commands ###
