"""added is_superuser column  table

Revision ID: d1dcadc2ed64
Revises: 3ce24933573d
Create Date: 2025-06-10 20:50:56.957044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dcadc2ed64'
down_revision: Union[str, None] = '3ce24933573d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True), schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser', schema='portfolio_pro_app')
    # ### end Alembic commands ###
