"""add column to portfolio project  table

Revision ID: fd0304efb730
Revises: 604ca4b1100c
Create Date: 2025-06-08 14:57:16.730566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0304efb730'
down_revision: Union[str, None] = '604ca4b1100c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_projects', sa.Column('project_category', sa.String(), nullable=True), schema='portfolio_pro_app')
    op.add_column('portfolio_projects', sa.Column('is_completed', sa.Boolean(), nullable=True), schema='portfolio_pro_app')
    op.add_column('portfolio_projects', sa.Column('is_concept', sa.Boolean(), nullable=True), schema='portfolio_pro_app')
    op.add_column('user_project_association', sa.Column('contribution', sa.String(), nullable=True), schema='portfolio_pro_app')
    op.alter_column('user_project_association', 'contribution_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True,
               schema='portfolio_pro_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_project_association', 'contribution_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               schema='portfolio_pro_app')
    op.drop_column('user_project_association', 'contribution', schema='portfolio_pro_app')
    op.drop_column('portfolio_projects', 'is_concept', schema='portfolio_pro_app')
    op.drop_column('portfolio_projects', 'is_completed', schema='portfolio_pro_app')
    op.drop_column('portfolio_projects', 'project_category', schema='portfolio_pro_app')
    # ### end Alembic commands ###
